# Parses the server-side sampler's CSV (bin/sample-server.sh).
#
# Client-side latency alone cannot say *what* ran out. A knee with the CPU trace
# pinned near 800% is an application limit; the same knee with CPU at 60% is
# not, and points at the wireless link or database write contention instead.
# That distinction is the reason this file is read at all.
module Analysis
  class ServerTrace
    Reading = Struct.new(:at, :cpu_pct, :mem_pct, :load1, :wal_bytes, :db_bytes)

    attr_reader :readings

    def initialize(readings)
      @readings = readings
    end

    def self.parse(path)
      return new([]) unless path && File.exist?(path)

      readings = []
      File.foreach(path).with_index do |line, index|
        next if index.zero? # header
        next if line.start_with?("#")

        at, cpu, mem, load1, wal, db = line.strip.split(",")
        timestamp = Integer(at, exception: false)
        next if timestamp.nil?

        readings << Reading.new(
          timestamp,
          Float(cpu, exception: false),
          Float(mem, exception: false),
          Float(load1, exception: false),
          Integer(wal, exception: false),
          Integer(db, exception: false)
        )
      end

      new(readings.sort_by(&:at))
    end

    def empty? = @readings.empty?

    def within(window)
      @readings.select { |r| r.cpu_pct && window.cover?(r.at) }
    end

    def average_cpu(window)
      sampled = within(window)
      return nil if sampled.empty?

      sampled.sum(&:cpu_pct) / sampled.length
    end

    def peak_cpu(window)
      within(window).map(&:cpu_pct).max
    end

    # Peaks are always scoped to a window rather than taken over the whole file.
    #
    # A server.csv is not guaranteed to describe only its own run: until the
    # sampler's process handling was fixed, every run.sh invocation leaked a
    # remote sampling loop that kept appending to that run's file for as long as
    # an hour, recording load generated by *later* runs. Bounding on the run's
    # own time window makes the numbers correct regardless.
    def peak_cpu(window)
      within(window).map(&:cpu_pct).max
    end

    def peak_wal_bytes(window)
      @readings.select { |r| r.wal_bytes && window.cover?(r.at) }.map(&:wal_bytes).max
    end
  end
end
